name: Next Images
on:
  merge_group:
  pull_request:
    branches:
      - next
    paths-ignore:
      - ".github/workflows/*iso*.yml"
      - ".github/workflows/*validate*.yml"
      - "**.md"
      - "flatpaks/**"
      - "iso_files/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-next:
    name: Build Next Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["bluefin"]
    with:
      image_flavors: '["main", "nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: next
      stream_aliases: latest

  generate-release:
    name: Generate Release
    needs: [build-image-next]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["next"]'
